### ISSUE TITLE
Doesn't exist in Integration list

### ISSUE THREAD

**Issue by pniewiadowski** [marciogranzotto/hass-smartthinq#10]
I've installed this add on through HACS, restarted HA and can't see it in Integration list menu, so can't go through config flow.
Does anybody else has the same problem?

![image](https://user-images.githubusercontent.com/28837813/115451191-2ac16200-a21d-11eb-98a5-1313391e31b0.png)

**Comment by jacekpaszkowski** [comment]
Try force refresh page. Eg. Ctrl+F5 in Chrome on Windows

**Comment by pniewiadowski** [comment]
@jacekpaszkowski was trying that, as well as Incognito mode

**Comment by jacekpaszkowski** [comment]
@pniewiadowski Maybe check logs for errors or warnings

**Comment by pniewiadowski** [comment]
@jacekpaszkowski found it. Was under a different name :)

![image](https://user-images.githubusercontent.com/28837813/115453295-c48a0e80-a21f-11eb-87ab-ec8c7afad7ea.png)
