### ISSUE TITLE
Window A/C units Not Reporting Status or Temperature  

### ISSUE THREAD

**Issue by trentjw** [marciogranzotto/hass-smartthinq#13]
Dual Inverter
Model # LW1517IVSM

responds to command but does not give any feedback or confirmation of any sort

**Comment by kannan-balasubramanian** [comment]
Same here, the newly added 2021 AC doesn't show any temperature.
The old 2019 though recognized doesn't have any entity.

**Comment by kannan-balasubramanian** [comment]
Duplicate of #9

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
