### ISSUE TITLE
Configuration instructions typo

### ISSUE THREAD

**Issue by sbrighty** [marciogranzotto/hass-smartthinq#15]
Step 2. mentions:

Choose "LG SmartThinQ v2 Appliances"

This should read:

Choose "SmartThinq v2 Appliances"

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
