### ISSUE TITLE
AC additional features - ionization

### ISSUE THREAD

**Issue by jacekpaszkowski** [marciogranzotto/hass-smartthinq#16]
Hi,

i have two units:
DM07RP.NSJ
DM12RP.NSJ

those AC has air ionization feature, any option to get state and control this feature? (v2 api)

Thank you for your hard work!

**Comment by animaensis** [comment]
Hi,
there is a Domoticz project in which there is support for ionizer so it might be possible to add support for ioniser
https://github.com/olinek2/LGAC_SmartT
I am also highly interested in adding that functionality

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
