### ISSUE TITLE
Add down, down left and down right to def swing_modes_index():

### ISSUE THREAD

**Issue by BasTooltagger** [marciogranzotto/hass-smartthinq#21]
It would be great if you could add down direction to def swing_modes_index(): if possible :)

**Comment by BasTooltagger** [comment]
Tried to add it myself. Didn't have the time to test is
`def swing_modes_index():
    from wideq import ACHSwingMode, ACVSwingMode

    # name: [horz_key, vert_key]
    return {
        "Off": [ACHSwingMode.OFF, ACVSwingMode.OFF],
        "Vertical": [ACHSwingMode.OFF, ACVSwingMode.ALL],
        "Horizontal": [ACHSwingMode.ALL, ACVSwingMode.OFF],
        "Vertical and Horizontal": [ACHSwingMode.ALL, ACVSwingMode.ALL],
        "Up Left": [ACHSwingMode.FIVE, ACVSwingMode.ONE],
        "Up Right": [ACHSwingMode.ONE, ACVSwingMode.ONE],
        "Up": [ACHSwingMode.ALL, ACVSwingMode.ONE],
        "Down Left": [ACHSwingMode.FIVE, ACVSwingMode.FIVE],
        "Down Right": [ACHSwingMode.ONE, ACVSwingMode.FIVE],
        "Down": [ACHSwingMode.ALL, ACVSwingMode.ONE],
    }


SWING_MODE_DEFAULT = "Unknown"`

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
