### ISSUE TITLE
LG AC does not work anymore

### ISSUE THREAD

**Issue by aalmarshad** [marciogranzotto/hass-smartthinq#22]
My ACs do not work anymore with HA. Please find the log below.

Logger: homeassistant.components.climate
Source: custom_components/thinq_v2/climate.py:121 
Integration: Climate (documentation, issues) 
First occurred: 4:00:47 PM (2 occurrences) 
Last logged: 4:03:28 PM

Error while setting up thinq_v2 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/thinq_v2/climate.py", line 79, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/thinq_v2/climate.py", line 99, in _ac_devices
    d = LGDevice(client, device, fahrenheit)
  File "/config/custom_components/thinq_v2/climate.py", line 121, in __init__
    self._ac = wideq.ACDevice(client, device)
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 456, in __init__
    self.model: ModelInfo = client.model_info(device)
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 248, in model_info
    self._model_info[url] = device.load_model_info()
  File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 321, in load_model_info
    return requests.get(self.model_info_url, verify=False).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 891, in json
    return complexjson.loads(
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mikesplain** [comment]
Yeah I just set this up for the first time and am running into this as well.

**Comment by mikesplain** [comment]
Based on some searching, this may be version releated. I'm running `2021.5.4`

**Comment by mikesplain** [comment]
Actually, this just started working for me after restarting HA (though I did this earlier). I think LG had an outage today, I had issues with their app earlier and it seems to be working now too.

**Comment by trentjw** [comment]
Mine quit working about two days ago my LG app is working fine

**Comment by marciogranzotto** [comment]
Weird. This component already uses `__init__.py` and `manifest.json`.
I'll take a look at it tomorrow

**Comment by andrebbruno** [comment]
> Weird. This component already uses `__init__.py` and `manifest.json`.
> I'll take a look at it tomorrow

thank you sir!

**Comment by marciogranzotto** [comment]
I can't reproduce the issue running on 2021.5.5.

Looking at the provided logs:
> Error while setting up thinq_v2 platform for climate
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/thinq_v2/climate.py", line 79, in async_setup_entry
> await hass.async_add_executor_job(
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/thinq_v2/climate.py", line 99, in _ac_devices
> d = LGDevice(client, device, fahrenheit)
> File "/config/custom_components/thinq_v2/climate.py", line 121, in **init**
> self._ac = wideq.ACDevice(client, device)
> File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 456, in **init**
> self.model: ModelInfo = client.model_info(device)
> File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 248, in model_info
> self._model_info[url] = device.load_model_info()
> File "/usr/local/lib/python3.8/site-packages/wideq/client.py", line 321, in load_model_info
> return requests.get(self.model_info_url, verify=False).json()
> File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 891, in json
> return complexjson.loads(
> File "/usr/local/lib/python3.8/site-packages/simplejson/**init**.py", line 525, in loads
> return _default_decoder.decode(s)
> File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
> obj, end = self.raw_decode(s)
> File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
> return self.scan_once(s, idx=_w(s, idx).end())
> simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Looks like the problem is when `wideq` tries to read the `json` that LG returns...
Can you try using just my fork of wideq and see if you and get the json response?

**Comment by andrebbruno** [comment]
@marciogranzotto - When I first updated HA to 2021.5.5 I had the following error message, and the only thing I could do was to rever back to 21.5.2 to get the integration to work again:

![image](https://user-images.githubusercontent.com/53448558/119187667-08a34580-ba50-11eb-95ec-4bb954f3b0fc.png)


but now, after your message, I decided to create a snapshot of the current system and upgrade again to 2021.5.5 and it simply worked, no error messages whatsoever. Go figure

**Comment by marciogranzotto** [comment]
Hey guys, I'm deprecating this integration in favor of https://github.com/ollo69/ha-smartthinq-sensors since it now supports ACs in both thinq v1 and v2, and other features that this integration doesn't, like power monitoring and etc.

Thanks for using this integration while it lasted!
