### ISSUE TITLE
LG Ducted Air Conditioner doesn't report current temp or room temp?

### ISSUE THREAD

**Issue by jimmyleet** [marciogranzotto/hass-smartthinq#6]
Got this integration working! thank you for the amazing work, I can change the temp in home assistant however the integration doesn't report current set temp or the room temp.

Wondering if this is something I can fix?

I have attached my log if it helps, I am really new to HASS so if I have done something wrong with the log let me know.
[Log.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6343104/Log.txt)

**Comment by davewatson91** [comment]
Had the same issue. 

Check out PR #5 - there is a simple resolution for this - I have suggested a better solution, but don't have a means of doing this. 

Essentially just need to add `"AUTO": "auto",` after line 42 in climate.py

**Comment by jimmyleet** [comment]
> Had the same issue.
> 
> Check out PR #5 - there is a simple resolution for this - I have suggested a better solution, but don't have a means of doing this.
> 
> Essentially just need to add `"AUTO": "auto",` after line 42 in climate.py

I added the line and reset my server, reloaded the addon but it still doesn't show anything in the temperature.

![image](https://user-images.githubusercontent.com/19773514/115389917-d1f1c980-a21c-11eb-815b-daa656d42726.png)

All it seemed to do was add the "Auto" fan speed setting which wasn't there before

**Comment by davewatson91** [comment]
I have my money that you have a ducted system which doesn't have a 'swing' mode either? Can you pop another log dump through?

**Comment by jimmyleet** [comment]
Yeah it's a ducted no swing but it does have 8 zones connect to it which can be opened/closed on the app, not sure if ill get that control in home assistant tho lol

I've attached a new log if it's correct.
[Log.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6343374/Log.txt)

**Comment by davewatson91** [comment]
Your logs are showing the same swing error that came up on mine after the ‘auto’ speed was resolved. 

Check the first post in issue #4 for the resolution (band-aid). Just change the logic from == to != to force climate.py to ignore the swing.

**Comment by jimmyleet** [comment]
> Your logs are showing the same swing error that came up on mine after the ‘auto’ speed was resolved.
> 
> Check the first post in issue #4 for the resolution (band-aid). Just change the logic from == to != to force climate.py to ignore the swing.

Thanks for the tip, I did change that line and restart/reload the addon but still not showing temp/current temp I have attached another log file if it helps anyone.

[log.txt](https://github.com/marciogranzotto/hass-smartthinq/files/6343959/log.txt)

**Comment by davewatson91** [comment]
Great news! I think you can probably close this issue given the two problems are captured in others already. Glad you were able to get it going, I know it’s a huge thing in my household to be able to bridge it in with the rest of the smart home.
