### ISSUE TITLE
Finally got my AC's up and running

### ISSUE THREAD

**Issue by TheGabeMan** [marciogranzotto/hass-smartthinq#7]
Thank you! After waiting almost a year, I can get my LG AC's in HA. Just after they got installed here at home, LG switched to API v2, so I was unable to get them running in HA. Now it finally worked with your fork.

**Comment by Marcmk1** [comment]
Same here very happy!! Almost 2 years.
Was thinking to control it with InfraRed.
Damn, what was I'm hating myself to buying LG's : /
