### ISSUE TITLE
Mixed v1 and v2 devices?

### ISSUE THREAD

**Issue by adrianrdzv** [marciogranzotto/hass-smartthinq#8]
Is there a way to run both original `hass-smartthinq` component in the same instance that this v2 version? 
I installed this version and the components sees the v1 devices (I see them as devices) but provides not entities to control them. And my original `hass-smarthinq` component that controls the v1 devices now is broken, because it seems to be using this wideq version instead of the original.
Any workaround for having both components (if it's not in the plan for this one to work for both v1 and v2 devices)

**Comment by kannan-balasubramanian** [comment]
@marciogranzotto I have zero clue about Python, but do please let us know if we can provide any help to support both v1 and v2 APIs.

**Comment by nurimoca** [comment]
I have the same issue. 4xmultisplit ac unit, on HA I get 4 devices but only 3 entities, I guess one of the units it's v1...

**Comment by marciogranzotto** [comment]
I'm deprecating this integration since https://github.com/ollo69/ha-smartthinq-sensors has updated their integration to support ACs (v1 and v2), and seems to be doing a better job at that, please just use that integration instead!
